name: crpto
description: "Simple description."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  custom_refresh_indicator: ^4.0.1
  carousel_slider: ^5.0.0
  auto_size_text: ^3.0.0
  equatable: ^2.0.7
  decimal: ^3.2.1
  rxdart: ^0.28.0
  intl: ^0.20.2
  cron: ^0.6.1
  uuid: ^4.5.1

  # state management
  flutter_riverpod: ^2.6.1
  provider: ^6.1.4

  # routing
  go_router: ^14.8.1

  # network
  web_socket_channel: ^3.0.2
  dio: ^5.8.0+1

  # graphics
  flutter_svg: ^2.0.17
  vector_graphics: ^1.1.18
  fl_chart: ^0.70.2
  shimmer: ^3.0.0

  # local storage
  shared_preferences: ^2.5.2
  drift_flutter: ^0.2.4
  drift: ^2.26.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.0.4
  json_serializable: ^6.9.4
  drift_dev: ^2.26.0

  riverpod_generator: ^2.6.5
  retrofit_generator: ^9.1.9

  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

  vector_graphics_compiler: ^1.1.16

  build_runner: ^2.4.15

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/svgs_vec/
    - assets/svgs/common/
    - assets/svgs/tokens/
    - assets/svgs/tokens/
    - assets/svgs_vec/tokens/
    - assets/svgs_vec/tokens/