name: crpto
description: "Simple description."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.2.1
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  # state management
  flutter_riverpod: ^2.6.1

  # routing
  go_router: ^14.8.0

  # network
  web_socket_channel: ^3.0.2
  retrofit: ^4.4.2
  dio: ^5.8.0+1

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^2.5.8
  json_serializable: ^6.9.3
  riverpod_generator: ^2.6.4
  retrofit_generator: ^9.1.7
  build_runner: ^2.4.14
  riverpod_lint: ^2.6.4
  custom_lint: ^0.7.3

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
