name: crpto
description: "Simple description."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  package_info_plus: ^8.3.0
  riverpod_annotation: ^2.6.1
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  custom_refresh_indicator: ^4.0.1
  flutter_auto_size_text: ^4.1.0
  carousel_slider: ^5.1.1
  flutter_dotenv: ^5.2.1
  sliver_tools: ^0.2.12
  equatable: ^2.0.7
  decimal: ^3.2.4
  rxdart: ^0.28.0
  intl: ^0.20.2
  cron: ^0.6.2
  uuid: ^4.5.1

  # state management
  flutter_riverpod: ^2.6.1
  provider: ^6.1.5

  # routing
  go_router: ^16.0.0

  # network
  web_socket_channel: ^3.0.3
  dio: ^5.8.0+1

  # graphics
  flutter_svg: ^2.2.0
  vector_graphics: ^1.1.19
  cached_network_image: ^3.4.1
  fl_chart: ^1.0.0
  shimmer: ^3.0.0

  # local storage
  shared_preferences: ^2.5.3
  drift_flutter: ^0.2.4
  drift: ^2.28.0

  # firebase
  firebase_analytics: ^12.0.0
  firebase_remote_config: ^6.0.0
  firebase_core: ^4.0.0

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  freezed: ^3.1.0
  json_serializable: ^6.9.5
  drift_dev: ^2.28.0

  riverpod_generator: ^2.6.5

  riverpod_lint: ^2.6.5
  custom_lint: ^0.7.5

  vector_graphics_compiler: ^1.1.17

  build_runner: ^2.5.4

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/svgs/
    - assets/svgs_vec/
    - assets/svgs/common/
    - assets/svgs/tokens/
    - assets/svgs/tokens/
    - assets/svgs_vec/tokens/
    - assets/svgs_vec/tokens/

    - .env
    - .env-dev