import 'package:flutter/services.dart';

abstract final class CryptoUtils {
  static final RegExp _iconNameRegex = RegExp(
    r'(?<=crypto_icons/)[^.]+(?=\.svg)',
  );

  static final List<String> _iconNames = [];

  static final Map<String, String> _displayNames = Map.unmodifiable({
    'btc': 'Bitcoin',
    'eth': 'Ethereum',
    'bnb': 'Binance Coin',
    'neo': 'Neo',
    'ltc': 'Litecoin',
    'qtum': 'Qtum',
    'ada': 'Cardano',
    'xrp': 'Ripple',
    'eos': 'EOS',
    'tusd': 'TrueUSD',
    'iota': 'IOTA',
    'xlm': 'Stellar',
    'ont': 'Ontology',
    'trx': 'Tron',
    'etc': 'Ethereum Classic',
    'icx': 'Icon',
    'nuls': 'Nuls',
    'vet': 'VeChain',
    'usdc': 'USD Coin',
    'link': 'Chainlink',
    'ong': 'Ontology Gas',
    'hot': 'Holo',
    'zil': 'Zilliqa',
    'zrx': '0x',
    'fet': 'Fetch.ai',
    'bat': 'Basic Attention Token',
    'zec': 'Zcash',
    'iost': 'IOST',
    'celr': 'Celer Network',
    'dash': 'Dash',
    'theta': 'Theta Network',
    'enj': 'Enjin Coin',
    'atom': 'Cosmos',
    'tfuel': 'Theta Fuel',
    'one': 'Harmony',
    'algo': 'Algorand',
    'doge': 'Dogecoin',
    'dusk': 'Dusk Network',
    'ankr': 'Ankr',
    'win': 'Wink',
    'cos': 'Contentos',
    'mtl': 'Metal',
    'dent': 'Dent',
    'wan': 'Wanchain',
    'fun': 'FunFair',
    'cvc': 'Civic',
    'chz': 'Chiliz',
    'band': 'Band Protocol',
    'xtz': 'Tezos',
    'rvn': 'Ravencoin',
    'hbar': 'Hedera Hashgraph',
    'nkn': 'NKN',
    'stx': 'Stacks',
    'kava': 'Kava',
    'arpa': 'ARPA Chain',
    'iotx': 'IoTeX',
    'rlc': 'iExec RLC',
    'ctxc': 'Cortex',
    'bch': 'Bitcoin Cash',
    'troy': 'Troy',
    'vite': 'Vite',
    'ftt': 'FTX Token',
    'eur': 'Euro Token',
    'ogn': 'Origin Protocol',
    'lsk': 'Lisk',
    'bnt': 'Bancor',
    'lto': 'LTO Network',
    'mbl': 'MovieBloc',
    'coti': 'COTI',
    'stpt': 'Standard Tokenization Protocol',
    'data': 'Streamr DATAcoin',
    'sol': 'Solana',
    'ctsi': 'Cartesi',
    'hive': 'Hive',
    'chr': 'Chromia',
    'ardr': 'Ardor',
    'mdt': 'Measurable Data Token',
    'stmx': 'StormX',
    'knc': 'Kyber Network',
    'lrc': 'Loopring',
    'comp': 'Compound',
    'sc': 'Siacoin',
    'zen': 'Horizen',
    'snx': 'Synthetix',
    'vtho': 'VeThor Token',
    'dgb': 'DigiByte',
    'sxp': 'Swipe',
    'mkr': 'Maker',
    'dcr': 'Decred',
    'storj': 'Storj',
    'mana': 'Decentraland',
    'yfi': 'yearn.finance',
    'bal': 'Balancer',
    'kmd': 'Komodo',
    'jst': 'JUST',
    'crv': 'Curve DAO Token',
    'sand': 'The Sandbox',
    'nmr': 'Numeraire',
    'dot': 'Polkadot',
    'luna': 'Terra',
    'rsr': 'Reserve Rights',
    'paxg': 'PAX Gold',
    'trb': 'Tellor',
    'sushi': 'SushiSwap',
    'ksm': 'Kusama',
    'egld': 'Elrond',
    'dia': 'DIA',
    'rune': 'THORChain',
    'fio': 'FIO Protocol',
    'uma': 'UMA',
    'bel': 'Bella Protocol',
    'wing': 'Wing Finance',
    'uni': 'Uniswap',
    'oxt': 'Orchid',
    'sun': 'SUN',
    'avax': 'Avalanche',
    'flm': 'Flamingo',
    'utk': 'Utrust',
    'xvs': 'Venus',
    'alpha': 'Alpha Finance',
    'aave': 'Aave',
    'near': 'NEAR Protocol',
    'fil': 'Filecoin',
    'inj': 'Injective Protocol',
    'audio': 'Audius',
    'ctk': 'CertiK',
    'axs': 'Axie Infinity',
    'hard': 'HARD Protocol',
    'strax': 'Stratis',
    'rose': 'Oasis Network',
    'ava': 'Travala.com',
    'skl': 'SKALE',
    'grt': 'The Graph',
    'juv': 'Juventus Fan Token',
    'psg': 'Paris Saint-Germain Fan Token',
    '1inch': '1inch',
    'og': 'OG Fan Token',
    'atm': 'Atletico Madrid Fan Token',
    'asr': 'AS Roma Fan Token',
    'celo': 'Celo',
    'rif': 'RSK Infrastructure Framework',
    'tru': 'TrueFi',
    'ckb': 'Nervos Network',
    'twt': 'Trust Wallet Token',
    'firo': 'Firo',
    'sfp': 'SafePal',
    'dodo': 'DODO',
    'cake': 'PancakeSwap',
    'acm': 'AC Milan Fan Token',
    'badger': 'Badger DAO',
    'fis': 'StaFi',
    'om': 'MANTRA',
    'pond': 'Marlin',
    'dego': 'Dego Finance',
    'alice': 'My Neighbor Alice',
    'lina': 'Linear Finance',
    'perp': 'Perpetual Protocol',
    'super': 'SuperFarm',
    'cfx': 'Conflux Network',
    'tko': 'Tokocrypto',
    'pundix': 'Pundi X',
    'tlm': 'Alien Worlds',
    'bar': 'FC Barcelona Fan Token',
    'forth': 'Ampleforth Governance Token',
    'bake': 'BakerySwap',
    'burger': 'BurgerSwap',
    'slp': 'Smooth Love Potion',
    'shib': 'Shiba Inu',
    'icp': 'Internet Computer',
    'ar': 'Arweave',
    'mask': 'Mask Network',
    'lpt': 'Livepeer',
    'xvg': 'Verge',
    'ata': 'Automata',
    'gtc': 'Gitcoin',
    'ern': 'Ethernity',
    'pha': 'Phala Network',
    'mln': 'Enzyme',
    'dexe': 'DeXe',
    'c98': 'Coin98',
    'clv': 'Clover Finance',
    'qnt': 'Quant',
    'flow': 'Flow',
    'mina': 'Mina Protocol',
    'ray': 'Raydium',
    'farm': 'Harvest Finance',
    'alpaca': 'Alpaca Finance',
    'quick': 'QuickSwap',
    'mbox': 'MOBOX',
    'req': 'Request',
    'ghst': 'Aavegotchi',
    'waxp': 'WAX',
    'gno': 'Gnosis',
    'xec': 'eCash',
    'elf': 'aelf',
    'dydx': 'dYdX',
    'idex': 'IDEX',
    'vidt': 'VIDT Datalink',
    'usdp': 'Pax Dollar',
    'gala': 'Gala',
    'ilv': 'Illuvium',
    'ygg': 'Yield Guild Games',
    'sys': 'Syscoin',
    'df': 'dForce',
    'fida': 'Bonfida',
    'agld': 'Adventure Gold',
    'rad': 'Radicle',
    'beta': 'Beta Finance',
    'rare': 'SuperRare',
    'lazio': 'Lazio Fan Token',
    'chess': 'Tranchess',
    'adx': 'AdEx',
    'auction': 'Bounce Token',
    'bnx': 'BinaryX',
    'movr': 'Moonriver',
    'city': 'Manchester City Fan Token',
    'ens': 'Ethereum Name Service',
    'qi': 'BENQI',
    'porto': 'FC Porto Fan Token',
    'powr': 'Power Ledger',
    'jasmy': 'JasmyCoin',
    'amp': 'Amp',
    'pyr': 'Vulcan Forged PYR',
    'alcx': 'Alchemix',
    'santos': 'Santos FC Fan Token',
    'bico': 'Biconomy',
    'flux': 'Flux',
    'fxs': 'Frax Share',
    'voxel': 'Voxies',
    'high': 'Highstreet',
    'cvx': 'Convex Finance',
    'people': 'ConstitutionDAO',
    'spell': 'Spell Token',
    'joe': 'Trader Joe',
    'ach': 'Alchemy Pay',
    'imx': 'Immutable X',
    'glmr': 'Moonbeam',
    'loka': 'League of Kingdoms',
    'scrt': 'Secret',
    'api3': 'API3',
    'bttc': 'BitTorrent-New',
    'aca': 'Acala Token',
    'xno': 'Nano',
    'woo': 'WOO Network',
    'alpine': 'Alpine F1 Team Fan Token',
    't': 'Threshold',
    'astr': 'Astar',
    'gmt': 'STEPN',
    'kda': 'Kadena',
    'ape': 'ApeCoin',
    'bsw': 'Biswap',
    'bifi': 'Beefy.Finance',
    'steem': 'Steem',
    'nexo': 'Nexo',
    'rei': 'REI Network',
    'ldo': 'Lido DAO',
    'op': 'Optimism',
    'lever': 'LeverFi',
    'stg': 'Stargate Finance',
    'lunc': 'Terra Classic',
    'gmx': 'GMX',
    'polyx': 'PolySwarm',
    'apt': 'Aptos',
    'osmo': 'Osmosis',
    'hft': 'Hashflow',
    'phb': 'Phoenix Global',
    'hook': 'Hooked Protocol',
    'magic': 'Magic',
    'hifi': 'Hifi Finance',
    'rpl': 'Rocket Pool',
    'pros': 'Prosper',
    'gns': 'Gains Network',
    'syn': 'Synapse',
    'vib': 'Viberate',
    'ssv': 'SSV Network',
    'lqty': 'Liquity',
    'amb': 'Ambrosus',
    'ustc': 'TerraClassicUSD',
    'gas': 'Gas',
    'glm': 'Golem',
    'prom': 'Prometeus',
    'qkc': 'QuarkChain',
    'uft': 'UniLend',
    'id': 'SPACE ID',
    'arb': 'Arbitrum',
    'rdnt': 'Radiant Capital',
    'wbtc': 'Wrapped Bitcoin',
    'edu': 'EduCoin',
    'sui': 'Sui',
    'aergo': 'Aergo',
    'pepe': 'Pepe',
    'floki': 'Floki Inu',
    'ast': 'AirSwap',
    'snt': 'Status',
    'combo': 'Furucombo',
    'mav': 'Maverick Protocol',
    'pendle': 'Pendle',
    'arkm': 'Arkham',
    'wbeth': 'Wrapped Beacon ETH',
    'wld': 'Worldcoin',
    'fdusd': 'First Digital USD',
    'sei': 'Sei',
    'cyber': 'CyberConnect',
    'ark': 'Ark',
    'cream': 'Cream Finance',
    'iq': 'Everipedia',
    'ntrn': 'Neutron',
    'tia': 'Celestia',
    'meme': 'Memetic',
    'ordi': 'Ordinals',
    'beamx': 'BeamX',
    'pivx': 'PIVX',
    'vic': 'VIC',
    'blur': 'Blur',
    'vanry': 'Vanity',
    'aeur': 'Augmint Euro',
    'jto': 'Justus',
    '1000sats': '1000 Satoshis',
    'bonk': 'Bonk',
    'ace': 'Ace',
    'nfp': 'New Frontier Presents',
    'ai': 'Artificial Intelligence',
    'xai': 'XAI',
    'manta': 'Manta Network',
    'alt': 'Altcoin',
    'jup': 'Jupiter',
    'pyth': 'Pyth Network',
    'ronin': 'Ronin',
    'dym': 'Dymmax',
    'pixel': 'Pixel',
    'strk': 'Strike',
    'portal': 'Portal',
    'pda': 'PlayDapp',
    'axl': 'Axelar',
    'wif': 'dogwifhat',
    'metis': 'MetisDAO',
    'aevo': 'Aevo',
    'bome': 'Book of Meme',
    'ethfi': 'Ether.fi',
    'ena': 'Ethena',
    'w': 'Wormhole',
    'tnsr': 'Tensor',
    'saga': 'Saga',
    'tao': 'Bittensor',
    'omni': 'Omni Network',
    'rez': 'Rez',
    'bb': 'BB Token',
    'not': 'Notcoin',
    'io': 'IO Coin',
    'zk': 'ZKsync',
    'lista': 'Lista DAO',
    'zro': 'LayerZero',
    'g': 'Golem',
    'banana': 'Banana Gun',
    'render': 'Render Token',
    'ton': 'Toncoin',
    'dogs': 'Dogs of Elon',
    'euri': 'Euro Coin',
    'slf': 'Self',
    'pol': 'Polygon Ecosystem Token',
    'neiro': 'Neiro AI',
    'turbo': 'Turbo',
    '1mbabydoge': '1 Million Baby Doge',
    'cati': 'Cat-in-a-Box',
    'hmstr': 'Hamster',
    'eigen': 'EigenLayer',
    'scr': 'Scorum',
    'bnsol': 'BonkSol',
    'lumia': 'Lumia',
    'kaia': 'Kaia AI',
    'cow': 'CoW Protocol',
    'cetus': 'Cetus Protocol',
    'pnut': 'Peanut',
    'act': 'Achain',
    'usual': 'Usual Token',
    'the': 'The Token',
    'acx': 'Access Protocol',
    'orca': 'Orca',
    'move': 'MOVEZ',
    'me': 'ME Token',
    'velodrome': 'Velodrome Finance',
    'vana': 'Vanar Chain',
    '1000cat': '1000Cats',
    'pengu': 'Penguin Finance',
    'bio': 'Biocoin',
    'd': 'Denarius',
    'aixbt': 'AI XBT',
    'cgpt': 'ChainGPT',
    'cookie': 'Cookie DAO',
    's': 'Sologenic',
    'solv': 'Solv Protocol',
    'trump': 'MAGA Trump Coin',
    'anime': 'Anime Token',
    'bera': 'Bera Chain',
    '1000cheems': '1000 Cheems',
    'tst': 'The Sandbox Testnet',
    'layer': 'LayerAI',
    'hei': 'Hei Token',
  });

  static Future<void> init() async {
    final assetManifest = await AssetManifest.loadFromAssetBundle(rootBundle);
    final cryptoIconPaths =
        assetManifest
            .listAssets()
            .where((path) => path.startsWith('assets/svgs/crypto_icons/'))
            .toList();

    _iconNames.addAll(
      cryptoIconPaths
          .map((path) => _iconNameRegex.firstMatch(path)?.group(0))
          .nonNulls
          .toList(),
    );
  }

  static String getDisplayName(String key) {
    return _displayNames[key.toLowerCase()] ?? 'N/A';
  }

  static String getSvgVecPath(String iconName) {
    return 'assets/svgs_vec/crypto_icons/${iconName.toLowerCase()}.svg.vec';
  }

  static String getSvgPath(String iconName) {
    return 'assets/svgs/crypto_icons/${iconName.toLowerCase()}.svg';
  }

  static bool isIconExists(String iconName) {
    return _iconNames.contains(iconName.toLowerCase());
  }
}
