// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaVGUjFETHBZU4Oool2iJI1W3bfn4gulU',
    appId: '1:736324598871:web:bf86ecbe2ff5f979a6f712',
    messagingSenderId: '736324598871',
    projectId: 'crpto-32bfe',
    authDomain: 'crpto-32bfe.firebaseapp.com',
    storageBucket: 'crpto-32bfe.firebasestorage.app',
    measurementId: 'G-FGKFJ6BW33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCs7s-9q4oxvhapvekHaPSc8378vZfWEvs',
    appId: '1:736324598871:android:4e88484e72268baea6f712',
    messagingSenderId: '736324598871',
    projectId: 'crpto-32bfe',
    storageBucket: 'crpto-32bfe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3TPdA59yL1s4-PDxOKOLwqMLm9znSJps',
    appId: '1:736324598871:ios:7d30a5284a2c8b5ea6f712',
    messagingSenderId: '736324598871',
    projectId: 'crpto-32bfe',
    storageBucket: 'crpto-32bfe.firebasestorage.app',
    iosBundleId: 'com.vmdev.crpto',
  );
}
