// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZrRlr2fpG2VaWpQdYjvlpu7TsTkcUfB0',
    appId: '1:654024963216:web:c40376e109e390cc6b1415',
    messagingSenderId: '654024963216',
    projectId: 'crpto-1b0a6',
    authDomain: 'crpto-1b0a6.firebaseapp.com',
    storageBucket: 'crpto-1b0a6.firebasestorage.app',
    measurementId: 'G-R70WY69WQW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLc0tql9RIHveik1pAi-EI3sRKaq94ZVQ',
    appId: '1:654024963216:android:ca987c7d2b7fa5dc6b1415',
    messagingSenderId: '654024963216',
    projectId: 'crpto-1b0a6',
    storageBucket: 'crpto-1b0a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ISaedhLq7um7QvtKmF7V_WA7-bOorIU',
    appId: '1:654024963216:ios:be990f5a52fc91266b1415',
    messagingSenderId: '654024963216',
    projectId: 'crpto-1b0a6',
    storageBucket: 'crpto-1b0a6.firebasestorage.app',
    iosBundleId: 'com.vmdev.crpto',
  );
}
